name: Convino CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Miniconda environment from environment.yml
      - name: Set up Conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          auto-update-conda: true
          activate-environment: convino

      # Step 3: Build Convino
      - name: Build Convino
        run: |
          make -j$(nproc)
          ls -l ./convino || echo "Convino binary not found!"

      - name: Run tests - simple
        run: |
          chmod +x test/run_tests.sh
          ./test/run_tests.sh simple

      - name: Run tests - advanced
        run: |
          chmod +x test/run_tests.sh
          ./test/run_tests.sh advanced

